### ISSUE TITLE
Not issues, I strongly like your Asymptote artworks and your Asymptote knowledge.

### ISSUE THREAD

**Issue by vuongtrong2143** [stla/hakyllsource#1]
I really like your Asymptote artworks very much.

I am learning Asymptote for drawing my pictures (2D and 3D). However, your Asymptote codes are only for 3D animations (Certainly, I will research about it in the future through your 3D codes).

I write this post **in the hope that**, you can create more several animations for 3D (includes 2D, something like [this ](https://commons.wikimedia.org/wiki/Category:Animations_of_curves) and [this](https://commons.wikimedia.org/wiki/Category:Animations_of_mathematics)).
Until now, my Asymptote knowledge is very basic.
Again, thanks for sharing your beautiful 3D Asymptote animations.

Best regards,
justonly

**Comment by stla** [comment]
Thanks @justonlyasy 👍
